version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: healenium-mongodb
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=healenium_user
      - MONGO_INITDB_ROOT_PASSWORD=mysecretpassword
      - MONGO_INITDB_DATABASE=healenium
    networks:
      - healenium

  healenium:
    image: healenium/hlm-backend:3.4.6
    container_name: healenium
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://healenium_user:mysecretpassword@mongodb:27017/healenium
      - KEY_SELECTOR_URL=false
      - COLLECT_METRICS=true
      - HLM_LOG_LEVEL=info
    restart: on-failure
    volumes:
      - ./container/logs/:/logs
    networks:
      - healenium
    depends_on:
      - mongodb

  selector-imitator:
    image: healenium/hlm-selector-imitator:1.4
    container_name: selector-imitator
    ports:
      - "8000:8000"
    restart: on-failure
    networks:
      - healenium
    depends_on:
      - healenium

volumes:
  mongodb_data:
    driver: local

networks:
  healenium:
    name: healenium
