version: "3.8"

services:
  postgres-db:
    image: postgres:15.5-alpine
    container_name: postgres-db
    ports:
      - "5430:5432"
    restart: always
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=healenium
      - POSTGRES_USER=healenium_user
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - healenium

  healenium:
    image: healenium/hlm-backend:3.4.6
    container_name: healenium
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/healenium?currentSchema=healenium
      - SPRING_POSTGRES_DB=healenium
      - SPRING_POSTGRES_SCHEMA=healenium
      - SPRING_POSTGRES_USER=healenium_user
      - SPRING_POSTGRES_PASSWORD=mysecretpassword
      - SPRING_POSTGRES_DB_HOST=postgres-db
      - KEY_SELECTOR_URL=false
      - COLLECT_METRICS=true
      - HLM_LOG_LEVEL=info
    restart: on-failure
    volumes:
      - ./container/logs/:/logs
    networks:
      - healenium
    depends_on:
      - postgres-db

  selector-imitator:
    image: healenium/hlm-selector-imitator:1.4
    container_name: selector-imitator
    ports:
      - "8000:8000"
    restart: on-failure
    networks:
      - healenium
    depends_on:
      - healenium

networks:
  healenium:
    name: healenium
