version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: healenium-mysql
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=healenium
      - MYSQL_USER=healenium_user
      - MYSQL_PASSWORD=mysecretpassword
    networks:
      - healenium

  healenium:
    image: healenium/hlm-backend:3.4.6
    container_name: healenium
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/healenium?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=healenium_user
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword
      - KEY_SELECTOR_URL=false
      - COLLECT_METRICS=true
      - HLM_LOG_LEVEL=info
    restart: on-failure
    volumes:
      - ./container/logs/:/logs
    networks:
      - healenium
    depends_on:
      - mysql

  selector-imitator:
    image: healenium/hlm-selector-imitator:1.4
    container_name: selector-imitator
    ports:
      - "8000:8000"
    restart: on-failure
    networks:
      - healenium
    depends_on:
      - healenium

volumes:
  mysql_data:
    driver: local

networks:
  healenium:
    name: healenium
